name: Pull Request Automations - General

on:
  [pull_request]

jobs:
  pr-automations-general:
    name: General applicable Automations for Pull Requests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Label PR type
      uses: TimonVS/pr-labeler-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Label PR size
      uses: "pascalgn/size-label-action@v0.4.2"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        IGNORED: ".gitignore\n.coveragerc\ncore/migrations/**"
      with:
        sizes: >
          {
            "0": "XS",
            "20": "S",
            "50": "M",
            "200": "L",
            "800": "XL",
            "2000": "XXL"
          }
      continue-on-error: true
